version: '3.3'

services:

  application:
    image:
      main-app
    build: ./examproject/
    container_name: 'main'
    ports:
      - "80:80"
    depends_on:
      - database
      - redis
      - rabbit
      - generator
    environment:
      - "DB_URL=jdbc:postgresql://database:5432/postgres"
      - "DB_USERNAME=postgres"
      - "DB_PASSWORD=postgres"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "RABBIT_HOST=rabbit"
      - "RABBIT_PORT=5672"


  redis:
    image:
      redis
    container_name: 'redis'
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: always


  rabbit:
    image: rabbitmq:3.6-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image:
      postgres
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
    restart: always


  generator:
    image:
      pdf-generator
    build: ./pdfgenerator/
    container_name: 'pdf-generator'
    depends_on:
      - rabbit
    ports:
      - "8080:8080"
    environment:
      - "RABBIT_HOST=rabbit"
      - "RABBIT_PORT=5672"

volumes:
  database:
  redis: